eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-action/', include('user_app.urls')),
    path('', include('matches.urls'))
]


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

matches/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'matches'
urlpatterns = [
    path('all_matches/', all_matches, name='all-matches'),
    path('load_excel/', load_excel, name='load-excel'),
    path('delete/', delete, name='delete-all'),
    path('filters/', filters, name='filters'),
    path('add_match/', add_match, name='add-match'),
    path('', index, name='index')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register', views._register, name='register'),
    path('logout', views._logout, name='logout'),
    path('login', views._login, name='login'),
]

matches/models.py
from django.db import models

# Create your models here.


class Match(models.Model):
    date = models.DateField(auto_now=False)
    team1 = models.CharField(max_length=25)
    team2 = models.CharField(max_length=25)
    r_h = models.FloatField()
    r_a = models.FloatField()
    tp_h = models.PositiveIntegerField()
    tp_a = models.PositiveIntegerField()
    ap_h = models.PositiveIntegerField()
    ap_a = models.PositiveIntegerField()
    kp_h = models.PositiveIntegerField()
    kp_a = models.PositiveIntegerField()
    sy_h = models.PositiveIntegerField()
    sy_a = models.PositiveIntegerField()
    ph_h = models.PositiveIntegerField()
    pa_h = models.PositiveIntegerField()
    ob_h = models.PositiveIntegerField()
    ob_a = models.PositiveIntegerField()
    sht_h = models.PositiveIntegerField()
    sht_a = models.PositiveIntegerField()
    sht_all = models.PositiveIntegerField()
    g_h = models.PositiveIntegerField()
    g_a = models.PositiveIntegerField()
    g_all = models.PositiveIntegerField()
    cl_h = models.PositiveIntegerField()
    cl_a = models.PositiveIntegerField()
    result = models.CharField(max_length=1)
    ft = models.CharField(max_length=5)
    champ = models.CharField(max_length=15)

    objects = models.Manager()

    def __str__(self):
        return self.team1 + ' - ' + self.team2

user_app/models.py
from django.db import models

# Create your models here.

matches/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.views import View
from .excel import excel_to_db
import pandas as pd
from .models import Match
from django.core.paginator import Paginator
from django.shortcuts import render


def listing(request, matches):
    paginator = Paginator(matches, 10)
    page = request.GET.get('page')
    matches = paginator.get_page(page)
    return matches


def index(request):
    ctx = {}
    return render(request, 'index.html', ctx)


def add_match(request):
    return redirect('/admin/matches/match/add/')


def all_matches(request):
    ctx = {}
    matches = Match.objects.all()
    ctx['matches'] = listing(request, matches)
    return render(request, 'matches/all_matches.html', ctx)


def filters(request):
    ctx = {}
    if request.method == 'GET':
        ctx['matches'] = Match.objects.all()
        ctx['country'] = ''
        ctx['winner'] = ''
        return render(request, 'matches/filters.html', ctx)
    if request.method == 'POST':
        country = request.POST.get('country')
        winner = request.POST.get('winner')
        if country not in 'all':
            ctx['matches'] = Match.objects.filter(champ=country)
        if winner not in 'all':
            ctx['matches'] = Match.objects.filter(result=winner)
        if country not in 'all' and winner not in 'all':
            ctx['matches'] = Match.objects.filter(champ=country, result=winner)
        ctx['country'] = request.POST.get('country')
        ctx['winner'] = request.POST.get('winner')
        return render(request, 'matches/filters.html', ctx)


def load_excel(request):
    ctx = {}
    if request.POST.get('upload_btn') == 'Upload':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        if fs.exists(uploaded_file.name):
            fs.delete(uploaded_file.name)
        fs.save(uploaded_file.name, uploaded_file)
        df = pd.read_excel(uploaded_file, sheet_name='all')
        excel_to_db(df)
    return render(request, 'matches/load_excel.html', ctx)


def delete(request):
    ctx = {}
    ctx['matches'] = Match.objects.all()
    if request.method == 'GET':
        Match.objects.all().delete()
    return render(request, 'matches/all_matches.html', ctx)

user_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm


def _register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            # return render(request, 'matches:index')
            return redirect('matches:index')
    else:
        form = UserCreationForm()
    return render(request, 'user_app/signup.html', {'form': form})


def _logout(request):
    logout(request)
    return redirect('matches:index')


def _login(request):
    ctx = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect('matches:index')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            ctx['login_error'] = 'Wrong login or password'
            return render(request, 'user_app/login.html', ctx)
    else:
        return render(request, 'user_app/login.html', ctx)

eshop/templates/includes/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

eshop/templates/includes/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      {% if not request.user.is_authenticated %}
          <p class="nav-item" style="margin-right:20px">
            <a class="btn btn-outline-success" href="{% url 'register' %}">Sign in</a>
          </p>
          <p class="nav-item">
              <a class="btn btn-outline-success" href="{% url 'login' %}">Login</a>
          </p>
        {% else %}
      <a class="navbar-brand" href="{% url 'matches:all-matches' %}">All matches</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'matches:load-excel' %}" style="margin-left:20px">Load excel<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'matches:filters' %}" style="margin-left:20px">Filters<span class="sr-only">(current)</span></a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'matches:add-match' %}" style="margin-left:20px">Add Match<span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" style="margin-left:20px">Log out ({{ request.user.username }})</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </nav>
</header>

eshop/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Football statistic</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <style>
      #left{
        float: left;
      }
      #center{
        float: center;
      }
      #right{
        float: right;
      }
    </style>
</head>
<body>

{% include 'includes/header.html' %}

<div class="container">
    {% block body %}

    {% endblock %}
</div>

</body>
</html>

eshop/templates/matches/actions.html
{% extends index.html%}

eshop/templates/matches/all_matches.html
{% extends 'index.html' %}

{% block body %}

<div id="left">
    <h3 style="color: green">Football</h3>
</div>

<div id="right">
    <form action="{% url 'matches:delete-all' %}" method="get">
        <button class="btn btn-danger">Удалить все матчи</button>
    </form>
</div>

<div class="col-sm-12">
    <table class="table table-striped table-bordered dataTable no-footer" cellpadding="3px" align="center" style="font-size:10pt">
    <tr class="br">
        <th>DATE</th>
        <th>CHAMP</th>
        <th>TEAM 1</th>
        <th>TEAM 2</th>
        <th>r_h</th>
        <th>r_a</th>
        <th>tp_h</th>
        <th>tp_a</th>
        <th>ap_h</th>
        <th>ap_a</th>
        <th>kp_h</th>
        <th>kp_a</th>
        <th>sy_h</th>
        <th>sy_a</th>
    </tr>
        {% for match in matches %}
    <tr class="br">
        <th>{{ match.date }}</th>
        <th>{{ match.champ }}</th>
        <th>{{ match.team1 }}</th>
        <th>{{ match.team2 }}</th>
        <th>{{ match.r_h }}</th>
        <th>{{ match.r_a }}</th>
        <th>{{ match.tp_h }}</th>
        <th>{{ match.tp_a }}</th>
        <th>{{ match.ap_h }}</th>
        <th>{{ match.ap_a }}</th>
        <th>{{ match.kp_h }}</th>
        <th>{{ match.kp_a }}</th>
        <th>{{ match.sy_h }}</th>
        <th>{{ match.sy_a }}</th>
    </tr>
        {% endfor %}
</table>
</div>

<div class="pagination">
    <span class="step-links">
        {% if matches.has_previous %}
            <a href="?page={{ matches.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ matches.number }} of {{ matches.paginator.num_pages }}
        </span>

        {% if matches.has_next %}
            <a href="?page={{ matches.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

eshop/templates/matches/filters.html
{% extends 'index.html' %}

{% block body %}

<form class="form-inline" method="post">
    {% csrf_token %}
    <select class="form-control" id="Country" name="country" style="margin-left:15px">
        {% if country == 'england' %}
        <option value="england" selected>England</option>
        {% else %}
        <option value="england">England</option>
        {% endif %}

        {% if country == 'england2' %}
        <option value="england2" selected>England 2</option>
        {% else %}
        <option value="england2">England 2</option>
        {% endif %}

        {% if country == 'spain' %}
        <option value="spain" selected>Spain</option>
        {% else %}
        <option value="spain">Spain</option>
        {% endif %}

        {% if country == 'netherlands' %}
        <option value="netherlands" selected>Netherlands</option>
        {% else %}
        <option value="netherlands">Netherlands</option>
        {% endif %}

        {% if country == 'germany' %}
        <option value="germany" selected>Germany</option>
        {% else %}
        <option value="germany">Germany</option>
        {% endif %}

        {% if country == 'germany2' %}
        <option value="germany2" selected>Germany 2</option>
        {% else %}
        <option value="germany2">Germany 2</option>
        {% endif %}

        {% if country == 'italy' %}
        <option value="italy" selected>Italy</option>
        {% else %}
        <option value="italy">Italy</option>
        {% endif %}

        {% if country == 'italy' %}
        <option value="france" selected>France</option>
        {% else %}
        <option value="france">France</option>
        {% endif %}

        {% if country == 'all' %}
        <option value="all" selected>--all--</option>
        {% else %}
        <option value="all">--all--</option>
        {% endif %}
    </select>

    <select class="form-control" id="Winner" name="winner" style="margin-left:15px">
        {% if winner == '1' %}
        <option value="1" selected>Home</option>
        {% else %}
        <option value="1">Home</option>
        {% endif %}

        {% if winner == 'x' %}
        <option value="x" selected>Draw</option>
        {% else %}
        <option value="x">Draw</option>
        {% endif %}

        {% if winner == '2' %}
        <option value="2" selected>Away</option>
        {% else %}
        <option value="2">Away</option>
        {% endif %}

        {% if winner == 'all' %}
        <option value="all" selected>--all--</option>
        {% else %}
        <option value="all">--all--</option>
        {% endif %}
    </select>

    <div class="rest-item" align="right">
        <form action="{% url 'matches:filters' %}" method="post">
            <button class="btn btn-success" style="margin-left:15px">Apply</button>
        </form>
    </div>
</form>

<div class="col-sm-12" align="right" style="width:70%">
    <h4 align="center" style="color: blue">Football</h4>
    <table class="table table-striped table-bordered dataTable no-footer" cellpadding="3px"
           style="font-size:10pt">
    <tr class="br">
        <th>DATE</th>
        <th>CHAMP</th>
        <th>TEAM 1</th>
        <th>TEAM 2</th>
        <th>RESULT</th>
    </tr>
    {% for match in matches %}
    <tr class="br">
        <th>{{ match.date }}</th>
        <th>{{ match.champ }}</th>
        <th>{{ match.team1 }}</th>
        <th>{{ match.team2 }}</th>
        {% if match.result == '1' %}
        <th>Home</th>
        {% elif match.result == '2' %}
        <th>Away</th>
        {% else %}
        <th>Draw</th>
        {% endif %}
    </tr>
    {% endfor %}
</table>
</div>



{% endblock %}

eshop/templates/matches/load_excel.html
{% extends 'index.html' %}


{% block body %}
<p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="document">
        <button type="submit" name="upload_btn" value="Upload" class="btn btn-info">Upload File</button>
    </form>
</p>
{% endblock %}

eshop/templates/matches/reports.html
{% extends 'index.html' %}


{% block body %}
<p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="document">
        <button type="submit" name="upload_btn" value="Upload" class="btn btn-info">Upload File</button>
    </form>
</p>
{% endblock %}

eshop/templates/user_app/login.html
{% extends 'index.html' %}

{% block body %}
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label><br>
        <input class="" type="text" name="username" placeholder=""><br>
    </div>
    <div class="form-group">
        <label for="password">Password</label><br>
        <input class="" type="password" name="password" placeholder=""><br>

    </div>
    <button type="submit" class="btn btn-success">Login</button>
</form>

{% if login_error %}
<div class="alert alert-danger">
    {{ login_error }}
</div>

{% endif %}
{% endblock  %}

eshop/templates/user_app/signup.html
{% extends 'index.html' %}

{% block title %} Registration new user {% endblock %}
{% block body %}
<form action="{% url 'register' %}" method="post">
    <div class="form-group">
        {% csrf_token %}
        {% for field in form %}
        {% if field.errors %}
        <div class="alert alert-info" role="alert">
            {{field.errors}}
        </div>
        {% endif %}
        <div class="form-group">
            <label for="">{{ field.label }}</label><br>
            {{ field }}
        </div>

        {% endfor %}

        <button type="submit" class="btn btn-success">Register</button>
    </div>
</form>
{% endblock %}